import sys
import os

# 添加项目根目录到Python路径
sys.path.insert(0, os.path.abspath('.'))

from sqlalchemy import text
from sqlalchemy.orm import Session
from sqlalchemy import create_engine

# 数据库连接URL（使用DuckDB）
db_url = "duckdb:////Users/liupeng/workspace/quantcell/backend/data/quantcell.db"

# 创建引擎
engine = create_engine(db_url)

print("连接到数据库...")

# 使用Session执行修复
with Session(engine) as session:
    print("\n执行修复：将data_pool_assets表的id字段设置为自动递增...")
    try:
        # 对于DuckDB，我们需要重新创建表，因为ALTER COLUMN不支持修改DEFAULT
        
        # 1. 创建临时表，包含原有数据和自动生成的id
        session.execute(text("""
            CREATE TABLE temp_data_pool_assets AS 
            SELECT 
                row_number() OVER () AS id,
                pool_id,
                asset_id,
                asset_type,
                created_at,
                updated_at
            FROM data_pool_assets
        """))
        
        # 2. 删除原表
        session.execute(text("DROP TABLE data_pool_assets"))
        
        # 3. 重新创建表，使用DuckDB的IDENTITY语法实现自动递增主键
        session.execute(text("""
            CREATE TABLE data_pool_assets (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                pool_id INTEGER NOT NULL,
                asset_id VARCHAR NOT NULL,
                asset_type VARCHAR NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """))
        
        # 4. 将数据从临时表复制回新表
        session.execute(text("""
            INSERT INTO data_pool_assets (id, pool_id, asset_id, asset_type, created_at, updated_at)
            SELECT id, pool_id, asset_id, asset_type, created_at, updated_at
            FROM temp_data_pool_assets
        """))
        
        # 5. 删除临时表
        session.execute(text("DROP TABLE temp_data_pool_assets"))
        
        session.commit()
        print("修复成功：已将data_pool_assets表的id字段设置为自动递增主键")
    except Exception as e:
        session.rollback()
        print(f"修复失败: {e}")
    
    # 检查表结构
    print("\n修复后的表结构:")
    columns = session.execute(text("DESCRIBE data_pool_assets")).fetchall()
    for column in columns:
        print(f"{column[0]} | {column[1]} | {column[2]} | {column[3]}")
