"""Initial migration

Revision ID: 1a960941d752
Revises: 
Create Date: 2026-01-26 18:45:56.243596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a960941d752'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crypto_future_klines', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('crypto_spot_klines', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('crypto_symbols', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('data_pool_assets', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('data_pools', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('features', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('scheduled_tasks', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('stock_klines', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('strategies', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_system_config_key'), 'system_config', ['key'], unique=False)
    op.create_index(op.f('ix_system_config_name'), 'system_config', ['name'], unique=False)
    op.create_index(op.f('ix_system_config_plugin'), 'system_config', ['plugin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_config_plugin'), table_name='system_config')
    op.drop_index(op.f('ix_system_config_name'), table_name='system_config')
    op.drop_index(op.f('ix_system_config_key'), table_name='system_config')
    op.alter_column('strategies', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('stock_klines', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('scheduled_tasks', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('features', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('data_pools', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('data_pool_assets', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('crypto_symbols', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('crypto_spot_klines', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('crypto_future_klines', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
