"""add_strategy_model_and_update_worker

Revision ID: 8b8f30ec3699
Revises: fe4d07250fbb
Create Date: 2026-03-29 15:45:06.611248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8f30ec3699'
down_revision: Union[str, Sequence[str], None] = 'fe4d07250fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_worker_trade_symbol'), table_name='worker_trades')
    op.drop_index(op.f('idx_worker_trade_time'), table_name='worker_trades')
    op.drop_index(op.f('ix_worker_trades_id'), table_name='worker_trades')
    op.drop_index(op.f('ix_worker_trades_worker_id'), table_name='worker_trades')
    op.drop_table('worker_trades')
    op.drop_index(op.f('idx_worker_status_history'), table_name='worker_status_history')
    op.drop_index(op.f('ix_worker_status_history_id'), table_name='worker_status_history')
    op.drop_index(op.f('ix_worker_status_history_timestamp'), table_name='worker_status_history')
    op.drop_index(op.f('ix_worker_status_history_worker_id'), table_name='worker_status_history')
    op.drop_table('worker_status_history')
    op.drop_index(op.f('idx_worker_metric_time'), table_name='worker_metrics')
    op.drop_index(op.f('ix_worker_metrics_id'), table_name='worker_metrics')
    op.drop_index(op.f('ix_worker_metrics_timestamp'), table_name='worker_metrics')
    op.drop_index(op.f('ix_worker_metrics_worker_id'), table_name='worker_metrics')
    op.drop_table('worker_metrics')
    op.drop_index(op.f('ix_worker_capital_id'), table_name='worker_capital')
    op.drop_table('worker_capital')
    op.drop_index(op.f('idx_worker_performance_date'), table_name='worker_performance')
    op.drop_index(op.f('ix_worker_performance_date'), table_name='worker_performance')
    op.drop_index(op.f('ix_worker_performance_id'), table_name='worker_performance')
    op.drop_index(op.f('ix_worker_performance_worker_id'), table_name='worker_performance')
    op.drop_table('worker_performance')
    op.drop_index(op.f('idx_strategy_history_user_created'), table_name='strategy_history')
    op.drop_index(op.f('idx_strategy_history_user_valid'), table_name='strategy_history')
    op.drop_index(op.f('ix_strategy_history_created_at'), table_name='strategy_history')
    op.drop_index(op.f('ix_strategy_history_id'), table_name='strategy_history')
    op.drop_index(op.f('ix_strategy_history_is_valid'), table_name='strategy_history')
    op.drop_index(op.f('ix_strategy_history_user_id'), table_name='strategy_history')
    op.drop_table('strategy_history')
    op.drop_index(op.f('idx_worker_status'), table_name='workers')
    op.drop_index(op.f('idx_worker_strategy'), table_name='workers')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_name'), table_name='workers')
    op.drop_index(op.f('ix_workers_status'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('idx_thinking_chain_type_active'), table_name='thinking_chains')
    op.drop_index(op.f('idx_thinking_chain_type_created'), table_name='thinking_chains')
    op.drop_index(op.f('ix_thinking_chains_chain_type'), table_name='thinking_chains')
    op.drop_index(op.f('ix_thinking_chains_created_at'), table_name='thinking_chains')
    op.drop_index(op.f('ix_thinking_chains_id'), table_name='thinking_chains')
    op.drop_index(op.f('ix_thinking_chains_is_active'), table_name='thinking_chains')
    op.drop_table('thinking_chains')
    op.drop_index(op.f('ix_worker_risk_control_id'), table_name='worker_risk_control')
    op.drop_table('worker_risk_control')
    op.drop_index(op.f('idx_worker_parameter'), table_name='worker_parameters')
    op.drop_index(op.f('ix_worker_parameters_id'), table_name='worker_parameters')
    op.drop_index(op.f('ix_worker_parameters_worker_id'), table_name='worker_parameters')
    op.drop_table('worker_parameters')
    op.drop_index(op.f('idx_worker_log'), table_name='worker_logs')
    op.drop_index(op.f('idx_worker_log_level'), table_name='worker_logs')
    op.drop_index(op.f('ix_worker_logs_id'), table_name='worker_logs')
    op.drop_index(op.f('ix_worker_logs_level'), table_name='worker_logs')
    op.drop_index(op.f('ix_worker_logs_timestamp'), table_name='worker_logs')
    op.drop_index(op.f('ix_worker_logs_worker_id'), table_name='worker_logs')
    op.drop_table('worker_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_logs_worker_id'), 'worker_logs', ['worker_id'], unique=False)
    op.create_index(op.f('ix_worker_logs_timestamp'), 'worker_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_worker_logs_level'), 'worker_logs', ['level'], unique=False)
    op.create_index(op.f('ix_worker_logs_id'), 'worker_logs', ['id'], unique=False)
    op.create_index(op.f('idx_worker_log_level'), 'worker_logs', ['worker_id', 'level'], unique=False)
    op.create_index(op.f('idx_worker_log'), 'worker_logs', ['worker_id', 'timestamp'], unique=False)
    op.create_table('worker_parameters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('param_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('param_value', sa.TEXT(), nullable=False),
    sa.Column('param_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('min_value', sa.FLOAT(), nullable=True),
    sa.Column('max_value', sa.FLOAT(), nullable=True),
    sa.Column('options', sa.TEXT(), nullable=True),
    sa.Column('editable', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'param_name', name=op.f('unique_worker_parameter'))
    )
    op.create_index(op.f('ix_worker_parameters_worker_id'), 'worker_parameters', ['worker_id'], unique=False)
    op.create_index(op.f('ix_worker_parameters_id'), 'worker_parameters', ['id'], unique=False)
    op.create_index(op.f('idx_worker_parameter'), 'worker_parameters', ['worker_id', 'param_name'], unique=False)
    op.create_table('worker_risk_control',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('max_position_size', sa.FLOAT(), nullable=True),
    sa.Column('max_position_pct', sa.FLOAT(), nullable=True),
    sa.Column('max_open_positions', sa.INTEGER(), nullable=True),
    sa.Column('stop_loss_pct', sa.FLOAT(), nullable=True),
    sa.Column('stop_loss_amount', sa.FLOAT(), nullable=True),
    sa.Column('trailing_stop_pct', sa.FLOAT(), nullable=True),
    sa.Column('take_profit_pct', sa.FLOAT(), nullable=True),
    sa.Column('take_profit_amount', sa.FLOAT(), nullable=True),
    sa.Column('daily_loss_limit', sa.FLOAT(), nullable=True),
    sa.Column('daily_loss_amount', sa.FLOAT(), nullable=True),
    sa.Column('daily_trade_limit', sa.INTEGER(), nullable=True),
    sa.Column('max_slippage_pct', sa.FLOAT(), nullable=True),
    sa.Column('max_spread_pct', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    op.create_index(op.f('ix_worker_risk_control_id'), 'worker_risk_control', ['id'], unique=False)
    op.create_table('thinking_chains',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('chain_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('steps', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('system_prompt', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thinking_chains_is_active'), 'thinking_chains', ['is_active'], unique=False)
    op.create_index(op.f('ix_thinking_chains_id'), 'thinking_chains', ['id'], unique=False)
    op.create_index(op.f('ix_thinking_chains_created_at'), 'thinking_chains', ['created_at'], unique=False)
    op.create_index(op.f('ix_thinking_chains_chain_type'), 'thinking_chains', ['chain_type'], unique=False)
    op.create_index(op.f('idx_thinking_chain_type_created'), 'thinking_chains', ['chain_type', 'created_at'], unique=False)
    op.create_index(op.f('idx_thinking_chain_type_active'), 'thinking_chains', ['chain_type', 'is_active'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('strategy_id_old', sa.INTEGER(), nullable=True),
    sa.Column('exchange', sa.VARCHAR(length=50), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=50), nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), nullable=False),
    sa.Column('market_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('trading_mode', sa.VARCHAR(length=10), nullable=True),
    sa.Column('cpu_limit', sa.INTEGER(), nullable=True),
    sa.Column('memory_limit', sa.INTEGER(), nullable=True),
    sa.Column('env_vars', sa.TEXT(), nullable=True),
    sa.Column('config', sa.TEXT(), nullable=True),
    sa.Column('pid', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('stopped_at', sa.DATETIME(), nullable=True),
    sa.Column('strategy_name', sa.VARCHAR(), nullable=True),
    sa.Column('strategy_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id_old'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='unique_worker_name')
    )
    op.create_index(op.f('ix_workers_status'), 'workers', ['status'], unique=False)
    op.create_index(op.f('ix_workers_name'), 'workers', ['name'], unique=False)
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_index(op.f('idx_worker_strategy'), 'workers', ['strategy_id_old'], unique=False)
    op.create_index(op.f('idx_worker_status'), 'workers', ['status'], unique=False)
    op.create_table('strategy_history',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('requirement', sa.TEXT(), nullable=False),
    sa.Column('code', sa.TEXT(), nullable=False),
    sa.Column('explanation', sa.TEXT(), nullable=True),
    sa.Column('model_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.Column('tokens_used', sa.TEXT(), nullable=True),
    sa.Column('generation_time', sa.FLOAT(), nullable=True),
    sa.Column('is_valid', sa.BOOLEAN(), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_history_user_id'), 'strategy_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_strategy_history_is_valid'), 'strategy_history', ['is_valid'], unique=False)
    op.create_index(op.f('ix_strategy_history_id'), 'strategy_history', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_history_created_at'), 'strategy_history', ['created_at'], unique=False)
    op.create_index(op.f('idx_strategy_history_user_valid'), 'strategy_history', ['user_id', 'is_valid'], unique=False)
    op.create_index(op.f('idx_strategy_history_user_created'), 'strategy_history', ['user_id', 'created_at'], unique=False)
    op.create_table('worker_performance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('total_trades', sa.INTEGER(), nullable=True),
    sa.Column('winning_trades', sa.INTEGER(), nullable=True),
    sa.Column('losing_trades', sa.INTEGER(), nullable=True),
    sa.Column('total_profit', sa.FLOAT(), nullable=True),
    sa.Column('total_loss', sa.FLOAT(), nullable=True),
    sa.Column('gross_profit', sa.FLOAT(), nullable=True),
    sa.Column('net_profit', sa.FLOAT(), nullable=True),
    sa.Column('max_drawdown', sa.FLOAT(), nullable=True),
    sa.Column('max_drawdown_pct', sa.FLOAT(), nullable=True),
    sa.Column('sharpe_ratio', sa.FLOAT(), nullable=True),
    sa.Column('sortino_ratio', sa.FLOAT(), nullable=True),
    sa.Column('calmar_ratio', sa.FLOAT(), nullable=True),
    sa.Column('win_rate', sa.FLOAT(), nullable=True),
    sa.Column('profit_factor', sa.FLOAT(), nullable=True),
    sa.Column('avg_profit', sa.FLOAT(), nullable=True),
    sa.Column('avg_loss', sa.FLOAT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'date', name=op.f('unique_worker_performance_date'))
    )
    op.create_index(op.f('ix_worker_performance_worker_id'), 'worker_performance', ['worker_id'], unique=False)
    op.create_index(op.f('ix_worker_performance_id'), 'worker_performance', ['id'], unique=False)
    op.create_index(op.f('ix_worker_performance_date'), 'worker_performance', ['date'], unique=False)
    op.create_index(op.f('idx_worker_performance_date'), 'worker_performance', ['worker_id', 'date'], unique=False)
    op.create_table('worker_capital',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('initial_capital', sa.FLOAT(), nullable=True),
    sa.Column('current_capital', sa.FLOAT(), nullable=True),
    sa.Column('available_capital', sa.FLOAT(), nullable=True),
    sa.Column('frozen_capital', sa.FLOAT(), nullable=True),
    sa.Column('margin_used', sa.FLOAT(), nullable=True),
    sa.Column('margin_ratio', sa.FLOAT(), nullable=True),
    sa.Column('leverage', sa.FLOAT(), nullable=True),
    sa.Column('max_leverage', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    op.create_index(op.f('ix_worker_capital_id'), 'worker_capital', ['id'], unique=False)
    op.create_table('worker_metrics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('cpu_usage', sa.FLOAT(), nullable=True),
    sa.Column('memory_usage', sa.FLOAT(), nullable=True),
    sa.Column('memory_used_mb', sa.FLOAT(), nullable=True),
    sa.Column('memory_total_mb', sa.FLOAT(), nullable=True),
    sa.Column('network_in', sa.INTEGER(), nullable=True),
    sa.Column('network_out', sa.INTEGER(), nullable=True),
    sa.Column('active_tasks', sa.INTEGER(), nullable=True),
    sa.Column('queued_tasks', sa.INTEGER(), nullable=True),
    sa.Column('completed_tasks', sa.INTEGER(), nullable=True),
    sa.Column('failed_tasks', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_metrics_worker_id'), 'worker_metrics', ['worker_id'], unique=False)
    op.create_index(op.f('ix_worker_metrics_timestamp'), 'worker_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_worker_metrics_id'), 'worker_metrics', ['id'], unique=False)
    op.create_index(op.f('idx_worker_metric_time'), 'worker_metrics', ['worker_id', 'timestamp'], unique=False)
    op.create_table('worker_status_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('old_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('new_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_status_history_worker_id'), 'worker_status_history', ['worker_id'], unique=False)
    op.create_index(op.f('ix_worker_status_history_timestamp'), 'worker_status_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_worker_status_history_id'), 'worker_status_history', ['id'], unique=False)
    op.create_index(op.f('idx_worker_status_history'), 'worker_status_history', ['worker_id', 'timestamp'], unique=False)
    op.create_table('worker_trades',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('trade_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=50), nullable=False),
    sa.Column('side', sa.VARCHAR(length=10), nullable=False),
    sa.Column('order_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('fee', sa.FLOAT(), nullable=True),
    sa.Column('fee_currency', sa.VARCHAR(length=10), nullable=True),
    sa.Column('realized_pnl', sa.FLOAT(), nullable=True),
    sa.Column('realized_pnl_pct', sa.FLOAT(), nullable=True),
    sa.Column('entry_time', sa.DATETIME(), nullable=True),
    sa.Column('exit_time', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.create_index(op.f('ix_worker_trades_worker_id'), 'worker_trades', ['worker_id'], unique=False)
    op.create_index(op.f('ix_worker_trades_id'), 'worker_trades', ['id'], unique=False)
    op.create_index(op.f('idx_worker_trade_time'), 'worker_trades', ['worker_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_worker_trade_symbol'), 'worker_trades', ['worker_id', 'symbol'], unique=False)
    # ### end Alembic commands ###
