"""add_market_data_table

Revision ID: e1f4e8e164c3
Revises: 6
Create Date: 2026-03-03 15:18:43.990793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f4e8e164c3'
down_revision: Union[str, Sequence[str], None] = '6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=30, scale=8), nullable=True),
    sa.Column('price_change_24h', sa.DECIMAL(precision=30, scale=8), nullable=True),
    sa.Column('price_change_percent_24h', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('volume_24h', sa.DECIMAL(precision=40, scale=8), nullable=True),
    sa.Column('high_24h', sa.DECIMAL(precision=30, scale=8), nullable=True),
    sa.Column('low_24h', sa.DECIMAL(precision=30, scale=8), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', name='unique_market_data_symbol_exchange')
    )
    op.create_index(op.f('ix_market_data_exchange'), 'market_data', ['exchange'], unique=False)
    op.create_index(op.f('ix_market_data_id'), 'market_data', ['id'], unique=False)
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_id'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_exchange'), table_name='market_data')
    op.drop_table('market_data')
    # ### end Alembic commands ###
