"""add task_detail table

Revision ID: ed0da7529e75
Revises: e1f4e8e164c3
Create Date: 2026-03-04 21:19:57.097294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0da7529e75'
down_revision: Union[str, Sequence[str], None] = 'e1f4e8e164c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('status_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'symbol', 'interval', name='unique_task_symbol_interval')
    )
    op.create_index(op.f('ix_task_details_id'), 'task_details', ['id'], unique=False)
    op.create_index(op.f('ix_task_details_interval'), 'task_details', ['interval'], unique=False)
    op.create_index(op.f('ix_task_details_symbol'), 'task_details', ['symbol'], unique=False)
    op.create_index(op.f('ix_task_details_task_id'), 'task_details', ['task_id'], unique=False)
    op.drop_index(op.f('idx_worker_trade_symbol'), table_name='worker_trades')
    op.drop_index(op.f('idx_worker_trade_time'), table_name='worker_trades')
    op.drop_index(op.f('ix_worker_trades_id'), table_name='worker_trades')
    op.drop_index(op.f('ix_worker_trades_worker_id'), table_name='worker_trades')
    op.drop_table('worker_trades')
    op.drop_index(op.f('ix_worker_capital_id'), table_name='worker_capital')
    op.drop_table('worker_capital')
    op.drop_index(op.f('idx_worker_parameter'), table_name='worker_parameters')
    op.drop_index(op.f('ix_worker_parameters_id'), table_name='worker_parameters')
    op.drop_index(op.f('ix_worker_parameters_worker_id'), table_name='worker_parameters')
    op.drop_table('worker_parameters')
    op.drop_index(op.f('idx_worker_status_history'), table_name='worker_status_history')
    op.drop_index(op.f('ix_worker_status_history_id'), table_name='worker_status_history')
    op.drop_index(op.f('ix_worker_status_history_timestamp'), table_name='worker_status_history')
    op.drop_index(op.f('ix_worker_status_history_worker_id'), table_name='worker_status_history')
    op.drop_table('worker_status_history')
    op.drop_index(op.f('idx_worker_metric_time'), table_name='worker_metrics')
    op.drop_index(op.f('ix_worker_metrics_id'), table_name='worker_metrics')
    op.drop_index(op.f('ix_worker_metrics_timestamp'), table_name='worker_metrics')
    op.drop_index(op.f('ix_worker_metrics_worker_id'), table_name='worker_metrics')
    op.drop_table('worker_metrics')
    op.drop_index(op.f('idx_worker_performance_date'), table_name='worker_performance')
    op.drop_index(op.f('ix_worker_performance_date'), table_name='worker_performance')
    op.drop_index(op.f('ix_worker_performance_id'), table_name='worker_performance')
    op.drop_index(op.f('ix_worker_performance_worker_id'), table_name='worker_performance')
    op.drop_table('worker_performance')
    op.drop_index(op.f('idx_worker_log'), table_name='worker_logs')
    op.drop_index(op.f('idx_worker_log_level'), table_name='worker_logs')
    op.drop_index(op.f('ix_worker_logs_id'), table_name='worker_logs')
    op.drop_index(op.f('ix_worker_logs_level'), table_name='worker_logs')
    op.drop_index(op.f('ix_worker_logs_timestamp'), table_name='worker_logs')
    op.drop_index(op.f('ix_worker_logs_worker_id'), table_name='worker_logs')
    op.drop_table('worker_logs')
    op.drop_index(op.f('ix_worker_risk_control_id'), table_name='worker_risk_control')
    op.drop_table('worker_risk_control')
    op.drop_index(op.f('idx_worker_status'), table_name='workers')
    op.drop_index(op.f('idx_worker_strategy'), table_name='workers')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_name'), table_name='workers')
    op.drop_index(op.f('ix_workers_status'), table_name='workers')
    op.drop_table('workers')
    op.add_column('ai_models', sa.Column('proxy_enabled', sa.Boolean(), nullable=True))
    op.add_column('ai_models', sa.Column('proxy_url', sa.String(), nullable=True))
    op.add_column('ai_models', sa.Column('proxy_username', sa.String(), nullable=True))
    op.add_column('ai_models', sa.Column('proxy_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_models', 'proxy_password')
    op.drop_column('ai_models', 'proxy_username')
    op.drop_column('ai_models', 'proxy_url')
    op.drop_column('ai_models', 'proxy_enabled')
    op.create_table('workers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('strategy_id', sa.INTEGER(), nullable=True),
    sa.Column('exchange', sa.VARCHAR(length=50), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=50), nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), nullable=False),
    sa.Column('market_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('trading_mode', sa.VARCHAR(length=10), nullable=True),
    sa.Column('cpu_limit', sa.INTEGER(), nullable=True),
    sa.Column('memory_limit', sa.INTEGER(), nullable=True),
    sa.Column('env_vars', sa.TEXT(), nullable=True),
    sa.Column('config', sa.TEXT(), nullable=True),
    sa.Column('pid', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('stopped_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='unique_worker_name')
    )
    op.create_index(op.f('ix_workers_status'), 'workers', ['status'], unique=False)
    op.create_index(op.f('ix_workers_name'), 'workers', ['name'], unique=False)
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_index(op.f('idx_worker_strategy'), 'workers', ['strategy_id'], unique=False)
    op.create_index(op.f('idx_worker_status'), 'workers', ['status'], unique=False)
    op.create_table('worker_risk_control',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('max_position_size', sa.FLOAT(), nullable=True),
    sa.Column('max_position_pct', sa.FLOAT(), nullable=True),
    sa.Column('max_open_positions', sa.INTEGER(), nullable=True),
    sa.Column('stop_loss_pct', sa.FLOAT(), nullable=True),
    sa.Column('stop_loss_amount', sa.FLOAT(), nullable=True),
    sa.Column('trailing_stop_pct', sa.FLOAT(), nullable=True),
    sa.Column('take_profit_pct', sa.FLOAT(), nullable=True),
    sa.Column('take_profit_amount', sa.FLOAT(), nullable=True),
    sa.Column('daily_loss_limit', sa.FLOAT(), nullable=True),
    sa.Column('daily_loss_amount', sa.FLOAT(), nullable=True),
    sa.Column('daily_trade_limit', sa.INTEGER(), nullable=True),
    sa.Column('max_slippage_pct', sa.FLOAT(), nullable=True),
    sa.Column('max_spread_pct', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    op.create_index(op.f('ix_worker_risk_control_id'), 'worker_risk_control', ['id'], unique=False)
    op.create_table('worker_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_logs_worker_id'), 'worker_logs', ['worker_id'], unique=False)
    op.create_index(op.f('ix_worker_logs_timestamp'), 'worker_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_worker_logs_level'), 'worker_logs', ['level'], unique=False)
    op.create_index(op.f('ix_worker_logs_id'), 'worker_logs', ['id'], unique=False)
    op.create_index(op.f('idx_worker_log_level'), 'worker_logs', ['worker_id', 'level'], unique=False)
    op.create_index(op.f('idx_worker_log'), 'worker_logs', ['worker_id', 'timestamp'], unique=False)
    op.create_table('worker_performance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('total_trades', sa.INTEGER(), nullable=True),
    sa.Column('winning_trades', sa.INTEGER(), nullable=True),
    sa.Column('losing_trades', sa.INTEGER(), nullable=True),
    sa.Column('total_profit', sa.FLOAT(), nullable=True),
    sa.Column('total_loss', sa.FLOAT(), nullable=True),
    sa.Column('gross_profit', sa.FLOAT(), nullable=True),
    sa.Column('net_profit', sa.FLOAT(), nullable=True),
    sa.Column('max_drawdown', sa.FLOAT(), nullable=True),
    sa.Column('max_drawdown_pct', sa.FLOAT(), nullable=True),
    sa.Column('sharpe_ratio', sa.FLOAT(), nullable=True),
    sa.Column('sortino_ratio', sa.FLOAT(), nullable=True),
    sa.Column('calmar_ratio', sa.FLOAT(), nullable=True),
    sa.Column('win_rate', sa.FLOAT(), nullable=True),
    sa.Column('profit_factor', sa.FLOAT(), nullable=True),
    sa.Column('avg_profit', sa.FLOAT(), nullable=True),
    sa.Column('avg_loss', sa.FLOAT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'date', name=op.f('unique_worker_performance_date'))
    )
    op.create_index(op.f('ix_worker_performance_worker_id'), 'worker_performance', ['worker_id'], unique=False)
    op.create_index(op.f('ix_worker_performance_id'), 'worker_performance', ['id'], unique=False)
    op.create_index(op.f('ix_worker_performance_date'), 'worker_performance', ['date'], unique=False)
    op.create_index(op.f('idx_worker_performance_date'), 'worker_performance', ['worker_id', 'date'], unique=False)
    op.create_table('worker_metrics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('cpu_usage', sa.FLOAT(), nullable=True),
    sa.Column('memory_usage', sa.FLOAT(), nullable=True),
    sa.Column('memory_used_mb', sa.FLOAT(), nullable=True),
    sa.Column('memory_total_mb', sa.FLOAT(), nullable=True),
    sa.Column('network_in', sa.INTEGER(), nullable=True),
    sa.Column('network_out', sa.INTEGER(), nullable=True),
    sa.Column('active_tasks', sa.INTEGER(), nullable=True),
    sa.Column('queued_tasks', sa.INTEGER(), nullable=True),
    sa.Column('completed_tasks', sa.INTEGER(), nullable=True),
    sa.Column('failed_tasks', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_metrics_worker_id'), 'worker_metrics', ['worker_id'], unique=False)
    op.create_index(op.f('ix_worker_metrics_timestamp'), 'worker_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_worker_metrics_id'), 'worker_metrics', ['id'], unique=False)
    op.create_index(op.f('idx_worker_metric_time'), 'worker_metrics', ['worker_id', 'timestamp'], unique=False)
    op.create_table('worker_status_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('old_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('new_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_status_history_worker_id'), 'worker_status_history', ['worker_id'], unique=False)
    op.create_index(op.f('ix_worker_status_history_timestamp'), 'worker_status_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_worker_status_history_id'), 'worker_status_history', ['id'], unique=False)
    op.create_index(op.f('idx_worker_status_history'), 'worker_status_history', ['worker_id', 'timestamp'], unique=False)
    op.create_table('worker_parameters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('param_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('param_value', sa.TEXT(), nullable=False),
    sa.Column('param_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('min_value', sa.FLOAT(), nullable=True),
    sa.Column('max_value', sa.FLOAT(), nullable=True),
    sa.Column('options', sa.TEXT(), nullable=True),
    sa.Column('editable', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'param_name', name=op.f('unique_worker_parameter'))
    )
    op.create_index(op.f('ix_worker_parameters_worker_id'), 'worker_parameters', ['worker_id'], unique=False)
    op.create_index(op.f('ix_worker_parameters_id'), 'worker_parameters', ['id'], unique=False)
    op.create_index(op.f('idx_worker_parameter'), 'worker_parameters', ['worker_id', 'param_name'], unique=False)
    op.create_table('worker_capital',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('initial_capital', sa.FLOAT(), nullable=True),
    sa.Column('current_capital', sa.FLOAT(), nullable=True),
    sa.Column('available_capital', sa.FLOAT(), nullable=True),
    sa.Column('frozen_capital', sa.FLOAT(), nullable=True),
    sa.Column('margin_used', sa.FLOAT(), nullable=True),
    sa.Column('margin_ratio', sa.FLOAT(), nullable=True),
    sa.Column('leverage', sa.FLOAT(), nullable=True),
    sa.Column('max_leverage', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    op.create_index(op.f('ix_worker_capital_id'), 'worker_capital', ['id'], unique=False)
    op.create_table('worker_trades',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('trade_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=50), nullable=False),
    sa.Column('side', sa.VARCHAR(length=10), nullable=False),
    sa.Column('order_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('fee', sa.FLOAT(), nullable=True),
    sa.Column('fee_currency', sa.VARCHAR(length=10), nullable=True),
    sa.Column('realized_pnl', sa.FLOAT(), nullable=True),
    sa.Column('realized_pnl_pct', sa.FLOAT(), nullable=True),
    sa.Column('entry_time', sa.DATETIME(), nullable=True),
    sa.Column('exit_time', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.create_index(op.f('ix_worker_trades_worker_id'), 'worker_trades', ['worker_id'], unique=False)
    op.create_index(op.f('ix_worker_trades_id'), 'worker_trades', ['id'], unique=False)
    op.create_index(op.f('idx_worker_trade_time'), 'worker_trades', ['worker_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_worker_trade_symbol'), 'worker_trades', ['worker_id', 'symbol'], unique=False)
    op.drop_index(op.f('ix_task_details_task_id'), table_name='task_details')
    op.drop_index(op.f('ix_task_details_symbol'), table_name='task_details')
    op.drop_index(op.f('ix_task_details_interval'), table_name='task_details')
    op.drop_index(op.f('ix_task_details_id'), table_name='task_details')
    op.drop_table('task_details')
    # ### end Alembic commands ###
